
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kiel
 */
public class SolutionWindow extends JFrame {


    /**
     * Creates new form Solution
     */

    public SolutionWindow(Solution objSolution, String type) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle(type);
        List<String> sols = objSolution.getPathSol();
        int lengthPath = sols.size();
        int lengthWord = sols.get(0).length();

        jPanel1.setLayout(new GridLayout(lengthPath, lengthWord,5,5));
        int height = 60*lengthPath+100;
        if(height>800){
            height=800;
        }
        this.setSize(new Dimension(58*lengthWord+15,height));
        jPanel1.setBackground(Color.WHITE);

        String destWord = sols.get(0), prevWord = null;

        for(int i=lengthPath-1;i>=0;i--){
            String sol = sols.get(i);
            for(int j=0;j<lengthWord;j++){
                JLabel label = new JLabel(Character.toString(Character.toUpperCase(sol.charAt(j))),SwingConstants.CENTER);
                label.setOpaque(true);
                label.setVerticalAlignment(SwingConstants.CENTER);

                Color bgColor = Color.WHITE, borderColor = Color.GRAY, fgColor = Color.BLACK;
                int borderWidth = 2;
                if(i==0){
                    bgColor = new Color(51,102,0);
                    fgColor = Color.WHITE;
                }else if(i==lengthPath-1){
                    bgColor = new Color(192,192,192);
                }else if(sol.charAt(j)== destWord.charAt(j)){
                    bgColor = new Color(102,255,102);
                }

                if(prevWord!=null){
                    if(sol.charAt(j)!=prevWord.charAt(j)){
                        borderColor = Color.BLACK;
                        borderWidth = 6;
                    }
                }

                label.setBackground(bgColor);
                label.setBorder(BorderFactory.createLineBorder(borderColor, borderWidth));
                label.setFont(new Font("Arial",Font.BOLD,24));
                label.setForeground(fgColor);
                jPanel1.add(label);
            }
            prevWord = sol;
        }

        String formattedDuration = String.format("%.3f", objSolution.getDuration());

        jLabel1.setText("Path Length: "+(lengthPath-1));
        jLabel2.setText("Execution time: "+formattedDuration+" ms");
        jLabel3.setText("\nNodes visited: "+objSolution.getNodesVisited());
        this.getContentPane().setBackground(Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jScrollPane1 = new JScrollPane();
        jPanel1 = new JPanel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(255, 255, 255));
        setMaximumSize(new Dimension(2147483000, 2147483000));
        setResizable(false);

        jLabel1.setFont(new Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);

        jLabel2.setFont(new Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);

        jLabel3.setFont(new Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);

        jScrollPane1.setMaximumSize(new Dimension(32700, 32700));
        jScrollPane1.setViewportView(jPanel1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel3)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    // End of variables declaration
}