
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Label;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kiel
 */
public class SolutionWindow extends javax.swing.JFrame {
    
    
    /**
     * Creates new form Solution
     * @param  objSolution
     */
    
    public SolutionWindow(Solution objSolution) {
        initComponents();
        
        List<String> sols = objSolution.getPathSol();
        int lengthPath = sols.size();
        if(lengthPath==0){
            jPanel1.add(new JLabel("Solution not found for \nthe given starting word and destination word"));
            this.setSize(new Dimension(500,200));
            return;
        }
        
        int lengthWord = sols.get(0).length();

        jPanel1.setLayout(new GridLayout(lengthPath, lengthWord,5,5));        
        this.setSize(new Dimension(60*lengthWord,60*lengthPath+100));
        jPanel1.setBackground(Color.WHITE);
        
        String destWord = sols.get(0), prevWord = null;
        
        for(int i=lengthPath-1;i>=0;i--){
            String sol = sols.get(i);
            for(int j=0;j<lengthWord;j++){
                JLabel label = new JLabel(Character.toString(Character.toUpperCase(sol.charAt(j))),SwingConstants.CENTER);
                label.setOpaque(true);
                label.setVerticalAlignment(SwingConstants.CENTER);
                
                Color bgColor = Color.WHITE, borderColor = Color.GRAY, fgColor = Color.BLACK;
                int borderWidth = 2;
                if(i==0){
                    bgColor = new Color(51,102,0);
                    fgColor = Color.WHITE;
                }else if(i==lengthPath-1){
                    bgColor = new Color(192,192,192);
                }else if(sol.charAt(j)== destWord.charAt(j)){
                    bgColor = new Color(102,255,102); 
                }
                
                if(prevWord!=null){
                    if(sol.charAt(j)!=prevWord.charAt(j)){
                        borderColor = Color.BLACK;
                        borderWidth = 6;
                    }
                }
                
                label.setBackground(bgColor);
                label.setBorder(BorderFactory.createLineBorder(borderColor, borderWidth));
                label.setFont(new Font("Arial",Font.BOLD,24));
                label.setForeground(fgColor);
                jPanel1.add(label);
            }
            prevWord = sol;
        }
        
        jLabel1.setText("Path Length: "+(lengthPath-1));
        jLabel2.setText("Execution time: "+(objSolution.getDuration())+" ms");
        jLabel3.setText("\nNodes visited: "+objSolution.getNodesVisited());
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.getContentPane().setBackground(Color.WHITE);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
